### ISSUE TITLE
Unit of DXF files

### ISSUE THREAD

**Issue by fooker** [Yowkees/keyball#103]
The provided DXF files are (per design) untiless. They do not seem to be in millimeters nor inch. What is the unit of these files?

**Comment by Yowkees** [comment]
My Adobe Illustrator said 1 unit = 1 Points.
I am not good at DXF files. If you need another scaled DXF, Please tell me.
Thank you.

**Comment by fooker** [comment]
No worries. Usually it is 1 unit = 1 inch or 1 unit = 1 mm (preferred).

For the record: 1 point is 0.352778 mm.
