### ISSUE TITLE
can't combine KC_BTN1 with C(...)

### ISSUE THREAD

**Issue by koron** [Yowkees/keyball#150]
`C(KC_BTN1)` doesn't work.
Because, Keyball firmware implements own minimal MOUSE key feature for size.

**Comment by koron** [comment]
fixed by #152

**Comment by koron** [comment]
keycodeの判定時に`QK_MODS` を考慮しない値で比較していたため、
`C(KC_BTN1)` のようなmodifierを伴うキーコードが機能しなくなっていた。

* QK_MODS をあらかじめ消した上で比較するようにした
* KC_BTN1~8の場合はprocess_record_kbでtrueを返すようにした
  QK_MODS分をQMKに処置させるため

**Comment by Yowkees** [comment]
Keyballシリーズのソフトメンテナンスにご尽力いただき本当にありがとうございます！
私も気づいていなかった不具合でしたが益々ファームウェアの完成度が上がりました。
早速正規ファームウェアとして公開したいと思います。
誠にありがとうございます！！
