### ISSUE TITLE
Add pictures of keyboard models

### ISSUE THREAD

**Issue by kittydoor** [Yowkees/keyball#191]
When landing on the repository, there are no images in the README.md, so it is difficult to understand at a glance what the keyboards are like. It would be very helpful to have pictures embedded in the readme.

**Comment by AlgusDark** [comment]
This would be nice.

This is an example of a repo that has all the keyboards in an image:
https://github.com/pierrechevalier83/ferris

The readme in Keyball only mentions the 46 (and maybe that one is not manufactured?).

If @Yowkees  has a picture, I could help on creating a README in a PR.

**Comment by koron** [comment]
I told this with Yowkees-san, and I was given permission to use photos from the online store and build guides.

I'll take care of this. 👍

**Comment by koron** [comment]
I feel Keyball 44 is better.

![Keyball 39 from buildguide](https://raw.githubusercontent.com/Yowkees/keyball/main/keyball39/doc/rev1/images/kb39_001.jpg)
![Keyball 44 from buildguide](https://raw.githubusercontent.com/Yowkees/keyball/main/keyball44/doc/rev1/images/kb44_001.jpg)
![Keyball 46 from buildguide](https://raw.githubusercontent.com/Yowkees/keyball/main/keyball46/doc/rev1/images/yw001.jpg)
![Keyball 61 from buildguide](https://raw.githubusercontent.com/Yowkees/keyball/main/keyball61/doc/rev1/images/kb61_002.jpg)

**Comment by koron** [comment]
I'm going to use Keyball61's photo, it would be fit with OGP image.

**Comment by koron** [comment]
#346 is merged, which added top image.
