### ISSUE TITLE
エポキシ接着剤の着色についての言及を検討

### ISSUE THREAD

**Issue by koron** [Yowkees/keyball#2]
トラックボールケースにエポキシ接着剤を付ける時に
接着剤が透明がかった白なので
付いたかどうか非常に分かりにくく不安でした。

[ちょっと調べるとレジン用の着色剤など油性のものと相性が良い](https://sweetsdeco.co.kr/article.php?contentsno=159&lang=ja) ようです。
作りやすさを考慮すると接着剤を着色するというオプションに言及するのが良いのではないでしょうか。

**Comment by Yowkees** [comment]
いろいろ検討しまして、やはりセラミックボールは全数私がボンド付けして出荷することとしました。エポキシ接着剤は不要となります。
