### ISSUE TITLE
stl files for the trackball mount

### ISSUE THREAD

**Issue by shigmas** [Yowkees/keyball#200]
Since this has been out of stock for such a long time, I am looking at printing everything myself. I assume the trackball PCB in keyball46 is universal. But, it seems like there is no 3D printer files for the trackball mount.

Am I missing something?

**Comment by Yowkees** [comment]
Sorry. I have not released stl data of ball case, because it is not good design for 3D printing.

**Comment by shigmas** [comment]
Okay. I missed the one day it was available last time. I'll wait for the next time.
