### ISSUE TITLE
Left keyball PCB doesn't work

### ISSUE THREAD

**Issue by AlgusDark** [Yowkees/keyball#236]
Hi, I followed the tutorial for keyball44.
I'm in the testing part. I can't make the left PCB (the one without trackball) to work. 

I can write the hex on the pro micro, so that makes sure it works; but I just don't know what else could I do to test. I finished the trackball right hand side and everything works correctly.

Any tips would be helpful 🙏

This are the things I did:

- I tried to click reset button on PCB twice. Doesn't work.
- I tried to jump ground and reset while pro micro mounted on PCB. Doesn't work.
- if I do the above when the pro micro isn't attached to the PCB, I can write the hex. Once I insert it again, I can't make it work.
- I switched pro micro's and both work correct on the right hand side (the one with the trackball)
- I checked all the diode continuity (all working)

I also sent an email through the contact mail from shirogane-lab.com if you need more information from the purchase I can provide.

Thank you!

**Comment by Yowkees** [comment]
Hi. OK.
I want to see your PCB picture.
I will e-mail you. Thank you.
