### ISSUE TITLE
ダブルトラックボールにおけるポインタのhandness設定

### ISSUE THREAD

**Issue by koron** [Yowkees/keyball#27]
現在、ダブルトラックボール構成ではUSBを繋いだ側がポインタ、
繋いでいない側がスクロールとなっています。

これをconfig.hで左右により固定できるようにします。
ただしdual ballで使ってる人はほぼいないので後回し。

---

When you use Keyball with double ball combination,
a ball on USB connected side is treated as mouse move.
And other side ball is scroll wheel.

We make it configurable by config.h or so: depending right or left.
But this is low priority because there are few peoples who use double ball.

**Comment by koron** [comment]
需要が見込めないのでやらない、ということで閉じます。

---

I close this because I can't expect the demand.

**Comment by Yowkees** [comment]
dual ball仕様でKeyballを長いこと使ってみましたがなかなか２つのボールを活用できる方法が見つかっていません。
ゲーム用途、CAD用途等でハマる活用法があったら良かったのですが、今後そういう話をいただくことに期待したいです。
