### ISSUE TITLE
レイヤー３への切り替え不具合

### ISSUE THREAD

**Issue by Yowkees** [Yowkees/keyball#28]
最新ファームウェアにてレイヤー３への切り替えが出来ていないかも知れません。
レイヤー３はRGBの変更の他、トラックボールをスクロールに変える機能を持っています。
デフォルトキーマップでは左手親指の一番内側のキーに割り当てられています。

ご確認いただければ幸いです。

**Comment by koron** [comment]
https://github.com/Yowkees/keyball/pull/29 こちらでPRしたファームウェアを用いたところ、
問題なくレイヤー3への切り替えができていますので、そちらをお試しください。

なおリリース候補のファームウェアは現在準備中です。

**Comment by koron** [comment]
> なおリリース候補のファームウェアは現在準備中です

こちらにビルド済みファームウェアを置きました!

https://github.com/Yowkees/keyball/discussions/31

本当はタグ打ってGithubのリリースを作った方が良いのかもですが
あくまでも仮=RC1ということで。

**Comment by Yowkees** [comment]
ありがとうございました！確認します！

**Comment by Yowkees** [comment]
申し訳ありません。まったく問題なくレイヤー３使用できました！
これで今後のキット購入者への対応もばっちりだと思います。本当にありがとうございます！
