### ISSUE TITLE
VIAのPRODUCT_IDについて

### ISSUE THREAD

**Issue by Yowkees** [Yowkees/keyball#30]
VIA対応をするために、右きき版と左きき版のjsonファイルを作成しました。
VIAを起動した際に自動でどちらが接続されているか判別する方法として、PRODUCT_ID＝0001なら右、0002なら左と判定しようと考えています。
今はmake前にrev1/config.hの中を１→２と手で書き換えていますが、これが自動で切り替わるようにPRODUCT_IDの位置を変更できると嬉しいです。
それか別のアイデアがあればご提案いただければと思います。
ご検討いただければ幸いです。

**Comment by koron** [comment]
ああ僕がやっときますのでアサインお願いします。

* `1` = 右トラックボール
* `2` = 左トラックボール
* `3` = ダブルトラックボールとしときましょうか

**Comment by koron** [comment]
ビルド済みファームはここに上げておきました。

https://github.com/Yowkees/keyball/discussions/31#discussioncomment-927740

**Comment by Yowkees** [comment]
早速のご対応ありがとうございました！
