### ISSUE TITLE
Support RGB_MATRIX

### ISSUE THREAD

**Issue by hden** [Yowkees/keyball#317]
## これは何か

キー操作と連動した LED アニメーションを利用することが可能になります。

## 課題

```
RGB_MATRIX_ENABLE = no      # Enable RGB_MATRIX (not work yet)
```

[rules.mk](https://github.com/Yowkees/keyball/blob/main/qmk_firmware/keyboards/keyball/keyball61/rules.mk#L38) にも書かれていたとおり現状 RGB_MATRIX への対応が未実装だがたまたま成功例を発見しましたので共有します。

ref: https://note.com/co_ke/n/nf89d0de0d718

**Comment by koron** [comment]
There are no plans to support RGB_MATRIX.
Therefore, this issue will be closed for now.

However, pull requests to support it are welcome.

**Comment by koron** [comment]
RGB_MATRIXに対応する計画は現時点ではありません。
よって一旦このissueは閉じます。

しかしPRは歓迎します。
