### ISSUE TITLE
LEDのマーキングが判別しにくいのをフォローする

### ISSUE THREAD

**Issue by koron** [Yowkees/keyball#4]
製造時の個体差・誤差かもしれませんが
PCB上のLEDのマーキングがパッドに近く判別しにくかったです。

対処法としては以下が考えられます。

* 次回製造時に線描だけでなく、少し(1mmくらい?)離れた位置にドット等を追加する
* 全体を写した写真にマーキングの意味をアノテーションする

    アノテーションに使う画像の1候補

    ![](https://github.com/Yowkees/keyball/raw/main/keyball46/doc/rev1/images/yw082.jpg)

**Comment by Yowkees** [comment]
ご意見ありがとうございます。次回ロットよりシルクを変更します。
