### ISSUE TITLE
keyball61 rev2 トラックボールをつけるとトラックボール側（右側）の横四つのキーが反応しない

### ISSUE THREAD

**Issue by emp-temp** [Yowkees/keyball#402]
突然すみません。先日keyball61を遊舎工房にて購入し、トラックボールICを壊してしまったためshirogane labより購入させていただいたものです。届いたので取り付けたところ、写真にある通り4つのキーが反応しなくなってしまいました。トラックボール基盤を指す前まではちゃんと使えていました。解決する方法がわからないので教えていただけると幸いです。
![IMG_1992](https://github.com/Yowkees/keyball/assets/103437238/ced46bec-6277-4df7-a2bb-0e9fdde092ef)
![IMG_1991](https://github.com/Yowkees/keyball/assets/103437238/2278b4db-e559-41b9-9ce1-0bb153493b4d)

**Comment by Yowkees** [comment]
ご連絡ありがとうございます。
ご質問はDiscussionsに書いていただければ幸いです。気付くのが遅くなってしまいました。

症状了解しました。
下記画像の赤丸２か所が隣の端子とショートしてしまっているように見えます。
ご指摘の４キーはROW3という信号線を使用しており、ちょうど緑矢印の端子がROW3なので症状と合いそうです。

半田ごてでショートしている部分を加熱して、半田を引き離してください。

以上、お手数ですがご対応お願いいたします。

![kb61_4keyfix](https://github.com/Yowkees/keyball/assets/84209772/2a4e10a6-5e42-43b5-8c89-1e416b2c0417)
