### ISSUE TITLE
Sensor pcb broken

### ISSUE THREAD

**Issue by tangbonze** [Yowkees/keyball#444]
Hi there: I try to build a keyball by myself, found sensor pcb gerber you provide is broken. Could you please kindly check? Thanks a lot.

**Comment by tangbonze** [comment]
https://github.com/Yowkees/keyball/blob/main/keyball46/ball_design_data/Trackball_PCB_gerber.zip
here's the file.

**Comment by koron** [comment]
FYI @Yowkees

**Comment by KastenTaco** [comment]
This issue is still persisting it seems?

**Comment by tangbonze** [comment]
![image](https://github.com/Yowkees/keyball/assets/80433177/aa4126de-6846-4e65-8cd8-71fdd19286d7)
This is gerber file I upload to jlc. You can see it definitely broken.

**Comment by tangbonze** [comment]
any update? If this pcb is close source, please just let me know. thanks.

**Comment by tangbonze** [comment]
close this by myself since no response at all. If it is close sourced material, you can just say it.

**Comment by ya-luotao** [comment]
I also encountered the same issue; it seems that the drill layer is missing in the exported Gerber file.
