### ISSUE TITLE
Incorrect handedness since qmk 0.24.0

### ISSUE THREAD

**Issue by zhyu** [Yowkees/keyball#495]
The default behavior of `SPLIT_HAND_MATRIX_GRID` has been changed in https://github.com/qmk/qmk_firmware/pull/22775.

We need to define `SPLIT_HAND_MATRIX_GRID_LOW_IS_LEFT` to make keyball works with qmk 0.24.0.

**Comment by koron** [comment]
Currently, there are no reasons to use QMK 0.24.x.
So we won't do it now.

Of course, if we find out the benefits of going to 0.24 or higher, we'll do it then.

**Comment by koron** [comment]
There are no plans to respond at this time, so I close the issue.

Please let me know and re-open this if there are any benefits for 0.24 or later.
