### ISSUE TITLE
LEDの点灯順序を明示する

### ISSUE THREAD

**Issue by koron** [Yowkees/keyball#5]
LEDの点灯順序(配線順序)をビルドガイド中に明示してあると助かります。

SK6812mini-Eは慣れるとハンダ付けの失敗もそうそうしませんが
逆に言えば慣れない人はやはり失敗します。
そのような時に番号がふってあれば
どのLEDに問題があるのかが伝えやすくなります。

また少し慣れた人であれば配線順序がわかれば
それをもとに不良個所を推定でき自己解決しやすくなるでしょう。

**Comment by Yowkees** [comment]
次回ロットより番号を追加します！
