### ISSUE TITLE
Keyball61 on rp2040

### ISSUE THREAD

**Issue by idank** [Yowkees/keyball#572]
Hi,

I previously had success with Keyball44 conversion to rp2040, and now I tried to convert Keyball61 and run into some issues. I tried to disable all features and just test the keyboard matrix and got stuck there where no key presses are registered. I noticed Keyball61 uses custom matrix scanning code called "duplexmatrix" and this is my first suspect where the compatibility issue might be. @koron I see you write this code, any idea why this wouldn't work on rp2040? To rule out soldering issue, I tested the keyboard with pro micro and it is working.

Here are the changes I made to the firmware to compile it for rp2040: https://github.com/idank/qmk_firmware/commit/ef9a3dc0d333118c46261c93e8077ac369039972

The same repo has working rp2040 Keyball44 firmware.

**Comment by idank** [comment]
I managed to solve it by modernizing the matrix scanning code, see https://github.com/idank/qmk_firmware/commit/c78580f0a4dac67c98d7bfb61728288ecc524004.

**Comment by carlos-gtz** [comment]
@idank , what are the changes needed for the keyball44 to work with rp2040?

**Comment by idank** [comment]
You can find a working firmware on my clone https://github.com/idank/qmk_firmware/tree/dev-rp2040/keyboards/keyball

**Comment by ljmill** [comment]
@idank What all would be required to be changed to get the RP2040 to work with a Keyball39?

**Comment by podiki** [comment]
@idank Sorry to revive an old issue, but I just swapped in an rp2040 for my keyball61 and ran into this issue. While using the QMK converter (to `rp2040_ce`) seems to work fine for e.g. keyball44, there was an issue for keyball61. In my case the keyboard was never fully recognized/responsive. Using your changes to the matrix scanning code fixed it.

Any ideas for why exactly this happens? Something about how QMK converts or specifics of rp2040 needed in the duplex code?

(I guess could use a bunch of `#ifdef`s for what mcu is being used, if it is needed/wanted to keep the older duplexmatrix code)
