### ISSUE TITLE
組み立て済みボール読み取り基板について言及する

### ISSUE THREAD

**Issue by koron** [Yowkees/keyball#6]
購入したキットではボール読み取り基板が組み立て済みでした。

そのため [この手順](https://github.com/Yowkees/keyball/blob/main/keyball46/doc/rev1/buildguide_jp.md#%E3%83%9C%E3%83%BC%E3%83%AB%E8%AA%AD%E3%81%BF%E5%8F%96%E3%82%8A%E5%9F%BA%E6%9D%BF%E3%81%AE%E7%B5%84%E3%81%BF%E7%AB%8B%E3%81%A6) に到達した際に若干困惑しました。
ひとこと言及があると助かります。

**Comment by Yowkees** [comment]
ビルドガイドに組み立て済みである場合があることを追記しました。
