### ISSUE TITLE
ジャンパの基盤を剥離させてしまった。トラックボールが反応しない。keyball39

### ISSUE THREAD

**Issue by Dr-cafelatte** [Yowkees/keyball#677]
先日keyball39を購入させていただきました。
右手トラックボール側の光学センサー用信号線のジャンパ形成が上手くいかず、基盤が剥離してしまいました。
お手数ではございますが対処法があれば教えていただけますでしょうか。
![S__4513815_0](https://github.com/user-attachments/assets/f9657082-8d76-47cc-a850-d5963258f095)
![S__4513817_0](https://github.com/user-attachments/assets/7fa99a29-0e77-40fe-af14-cdeaff5d973f)

**Comment by Dr-cafelatte** [comment]
追記。
はんだが得意な人と確認し、画像のように右手トラックボール側表面を、クロスを作るようにジャンパを形成しましたが、変わらずOLEDの移動量も全て0のままでした。
![S__47448067](https://github.com/user-attachments/assets/ad62ae21-a418-4252-9fa8-4f6e52299f87)

**Comment by Yowkees** [comment]
ご連絡が遅くなり申し訳ありません。

修理の方法は適切です。
下記の同色同士が導通しているか、また違う色どうしがショートしてしまっていないかご確認をお願いします。

![Keyball39_trackfix](https://github.com/user-attachments/assets/bc38ff02-e0a5-42d9-9c05-2d018a8503ee)

**Comment by Dr-cafelatte** [comment]
違う色同士のショートは確認できませんでした。
また、青色同士のみ導通しておりませんでした。

**Comment by Yowkees** [comment]
ご確認ありがとうございます。
青点どうしが導通していなかったということで、下記画像の青点どうしをエナメル線か導線で接続してください。
これでトラックボール復活できると思います。
![39trabofix](https://github.com/user-attachments/assets/9a94dd82-55ec-4793-86e3-38dc7df57a69)

**Comment by Dr-cafelatte** [comment]
ありがとうございます！
無事トラックボールが反応するようになりました。
部品を買い替えることなく修理できると思っていなかったので本当に感謝しております。
忙しい中、迅速な対応ありがとうございました。
