### ISSUE TITLE
スクロール停止直後にcursorが, ピクピク動く現象が発生

### ISSUE THREAD

**Issue by kyo219** [Yowkees/keyball#695]
現象を説明するために動画を添付します. 
(説明性のため, 感度をあえて高くしています) 
https://github.com/user-attachments/assets/6cd648a3-709f-4034-a897-d821f863d7ee

- 同様の現象が起きている方はいらっしゃいますでしょうか? 
- 黒色のトラックボールを使用していますが, 他色の方が読み取り精度が良い等あればご教示いただきたいです. 
(というのも, センサー部分を直接指で触ってスクロールした場合, この現象が起きないため相性的な所を疑っています)

**Comment by kyo219** [comment]
トラックボール台がブカブカなことが問題な気がしてきました. 
現状ネジをしっかり閉めた状態ですが, 机の揺れ等でもトラックボールが揺れます（それによりcursorがピクピクする.

**Comment by Yowkees** [comment]
ご連絡ありがとうございます。

トラックボールが不安定ですか？
ブカブカというか、ボールはプラスチックケースには触らず、セラミックボール３個で支持されています。
私の手持ちのKeyballではキーボードを揺すってもボールやカーソルは動きません。
もしかするとセラミックボールが無くなっている、もしくはセラミックボール以外にボールに触れているものが無いかご確認お願いします。

**Comment by kyo219** [comment]
@Yowkees 

ご回答ありがとうございます.! 
こちら確認したところ, セラミックボールが無くなっておりました.. 

以下のような, 2mmタイプのセラミックボールを3つ購入すれば代替となりえますでしょうか？
https://www.monotaro.com/g/01218880/

**Comment by kyo219** [comment]
こちら、2mmタイプのセラミックボールを追加購入して、挿入したところ改善されました。
従ってclose
