### ISSUE TITLE
Keyball44 EN build guide does not have conthrough direction instructions

### ISSUE THREAD

**Issue by tschmoog** [Yowkees/keyball#696]
Hello! 

Thank you for creating such a cool and wonderful product. I am very excited to use and learn it, and had a lot of fun building it. 

I was following your English guide on how to build Keyball44, however, in this version there is no instruction showing which direction the conthrough pins should go. I can see this step is present in the JP versions and other Keyball versions.

Unfortunately, I saw this too late and so I put some of my conthrough pins in the wrong direction which caused some connection issues. I was able to fix it by soldering both sides (pro micro and PCB side) for anyone who has also made this error.

Can this step be added to that guide for future users? 

Thank you again and have a good day!

**Comment by Yowkees** [comment]
Thank you very much for choosing Keyball!
And thank you for your fixing buildguide.
